/// Flutter icons PerioIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PerioIcon
///      fonts:
///       - asset: fonts/PerioIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PerioIcon {
  PerioIcon._();

  static const _kFontFam = 'PerioIcon';
  //static const String _kFontPkg = null;

  static const IconData half_circle_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam);
}
